# These are supported funding model platforms.
# Replace the placeholders below to enable the "Sponsor this project" button.
#
# github: [username]
# patreon: # username
# open_collective: # project name
# ko_fi: # username
# tidelift: # platform-name/package-name
# community_bridge: # platform-name/package-name
# liberapay: # username
# issuehunt: # username
# otechie: # username
# lfx_crowdfunding: # platform-name/package-name
# custom: ["https://your-url-here"]
